'use client'

import { useCallback } from 'react'
import { Download, AlertCircle, RotateCcw } from 'lucide-react'
import { Toaster } from 'sonner'
import { useAnalysis } from '@/hooks/useAnalysis'
import { useApiKeys } from '@/hooks/useApiKeys'
import { AnalyzerForm } from '@/components/analyzer/AnalyzerForm'
import { ProgressIndicator } from '@/components/analyzer/ProgressIndicator'
import { ResultsTabs } from '@/components/analyzer/ResultsTabs'
import { Button } from '@/components/ui/button'
import type { AnalyzeParams, AnalysisResult } from '@/lib/types/analysis'

function generateMarkdown(result: AnalysisResult): string {
  const lines: string[] = []

  lines.push('# Ontologizer Analysis Report')
  lines.push('')
  lines.push(`**Processing Time:** ${result.processingTimeMs}ms`)
  lines.push(
    `**Main Topic:** ${result.topicalSalience.mainTopic || 'N/A'}`
  )
  lines.push(
    `**Salience Score:** ${result.topicalSalience.score}`
  )
  lines.push(`**Cached:** ${result.cached ? 'Yes' : 'No'}`)
  lines.push('')

  if (result.entities.length > 0) {
    lines.push('## Entities')
    lines.push('')
    lines.push('| Name | Type | Confidence | Wikipedia | Wikidata |')
    lines.push('|------|------|-----------|-----------|----------|')
    for (const e of result.entities) {
      lines.push(
        `| ${e.name} | ${e.type} | ${e.confidenceScore}% | ${e.wikipediaUrl || '-'} | ${e.wikidataUrl || '-'} |`
      )
    }
    lines.push('')
  }

  if (Object.keys(result.jsonLd).length > 0) {
    lines.push('## JSON-LD')
    lines.push('')
    lines.push('```json')
    lines.push(JSON.stringify(result.jsonLd, null, 2))
    lines.push('```')
    lines.push('')
  }

  if (result.recommendations.length > 0) {
    lines.push('## Recommendations')
    lines.push('')
    for (let i = 0; i < result.recommendations.length; i++) {
      const rec = result.recommendations[i]
      const prefix = rec.category ? `**[${rec.category}]** ` : ''
      lines.push(`${i + 1}. ${prefix}${rec.advice}`)
    }
    lines.push('')
  }

  if (result.salienceTips.length > 0) {
    lines.push('## Salience Tips')
    lines.push('')
    for (const tip of result.salienceTips) {
      lines.push(`- ${tip}`)
    }
    lines.push('')
  }

  if (result.fanoutAnalysis) {
    const f = result.fanoutAnalysis
    lines.push('## Fan-out Analysis')
    lines.push('')
    lines.push(`Semantic chunks extracted: ${f.chunksExtracted}`)
    lines.push('')
    if (f.error) {
      lines.push(`> **Fan-out unavailable:** ${f.error}`)
      lines.push('')
    } else if (f.analysis) {
      lines.push(f.analysis)
      lines.push('')
    } else {
      lines.push('> No fan-out analysis was generated.')
      lines.push('')
    }
  }

  lines.push('---')
  lines.push('')
  lines.push('## Need help with schema markup or AI-search optimization?')
  lines.push('')
  lines.push(
    'This analysis was generated by [Ontologizer](https://www.searchinfluence.com), a free tool from **Search Influence**.'
  )
  lines.push('')
  lines.push(
    'We help brands and universities turn entity, schema, and fan-out insights into measurable organic-search gains. If you want a second pair of eyes on this report — or help actually shipping the recommendations — [get in touch with Search Influence](https://www.searchinfluence.com/contact/).'
  )
  lines.push('')

  return lines.join('\n')
}

function downloadMarkdown(result: AnalysisResult) {
  const md = generateMarkdown(result)
  const blob = new Blob([md], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `ontologizer-report-${Date.now()}.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export default function Home() {
  const { step, result, error, enrichProgress, analyze, reset } = useAnalysis()
  const { apiHeaders } = useApiKeys()

  const isAnalyzing =
    step === 'extracting' ||
    step === 'enriching' ||
    step === 'generating' ||
    step === 'fanout'

  const handleSubmit = useCallback(
    (params: AnalyzeParams) => {
      analyze(params, apiHeaders)
    },
    [analyze, apiHeaders]
  )

  return (
    <section className="main-section">
      <div className="si-container">
        <Toaster position="top-right" />

        <div className="analyzer-intro">
          <h2>Analyze any page</h2>
          <p>
            Paste a URL (or raw HTML) and Ontologizer fetches the content,
            pulls out named entities, looks them up in Wikipedia, Wikidata,
            Google&#39;s Knowledge Graph and ProductOntology, then assembles
            production-ready JSON-LD plus SEO and salience recommendations.
          </p>
          <ul>
            <li>
              <strong>Best on one page at a time</strong> — a specific article,
              service, or product page beats a homepage.
            </li>
            <li>
              <strong>Fan-out is optional</strong> — tick it to also see how
              Google&#39;s AI Mode might decompose queries about the page.
            </li>
            <li>
              <strong>Your keys, your control</strong> — bring your own API
              keys for unlimited use, or sign in for 5 free analyses/month.
            </li>
          </ul>
        </div>

        <div className="form-card">
          <AnalyzerForm onSubmit={handleSubmit} isAnalyzing={isAnalyzing} />
        </div>

        {isAnalyzing && (
          <div className="form-card">
            <ProgressIndicator step={step} enrichProgress={enrichProgress} />
          </div>
        )}

        {step === 'error' && error && (
          <QuotaOrErrorCard error={error} />
        )}

        {result && (
          <div className="si-results">
            <div className="results-header">
              <div className="flex items-center justify-between flex-wrap gap-3">
                <h2>Results</h2>
                <div className="flex gap-2">
                  <Button
                    variant="secondary"
                    size="sm"
                    onClick={() => downloadMarkdown(result)}
                  >
                    <Download className="size-3.5" />
                    Download Markdown
                  </Button>
                  <Button variant="secondary" size="sm" onClick={reset}>
                    <RotateCcw className="size-3.5" />
                    New analysis
                  </Button>
                </div>
              </div>
            </div>
            <div className="content-area">
              <ResultsTabs result={result} />
            </div>
          </div>
        )}

        <FaqSection />
      </div>
    </section>
  )
}

function QuotaOrErrorCard({ error }: { error: string }) {
  const isQuota = /free tier limit|5\/month/i.test(error)
  if (!isQuota) {
    return (
      <div className="si-error flex items-start gap-3">
        <AlertCircle className="mt-0.5 size-5 shrink-0" />
        <div>
          <p className="font-semibold">Analysis failed</p>
          <p className="mt-1 text-sm opacity-90">{error}</p>
        </div>
      </div>
    )
  }

  const nextReset = new Date()
  nextReset.setMonth(nextReset.getMonth() + 1, 1)
  nextReset.setHours(0, 0, 0, 0)
  const resetLabel = nextReset.toLocaleDateString(undefined, {
    month: 'long',
    day: 'numeric',
  })

  return (
    <div className="rounded-xl border-2 border-[var(--orange-accent)] bg-[var(--si-slate)] p-6 text-white shadow-lg">
      <div className="flex items-start gap-4">
        <div className="flex size-12 shrink-0 items-center justify-center rounded-full bg-[var(--orange-accent)] text-white">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="size-6"
          >
            <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
            <path d="M7 11V7a5 5 0 0 1 10 0v4" />
          </svg>
        </div>
        <div className="flex-1">
          <h3 className="text-xl font-extrabold leading-tight">
            Free tier limit reached
          </h3>
          <p className="mt-2 text-white/90">
            You&apos;ve used all 5 free analyses for this month. Your quota
            resets on <strong>{resetLabel}</strong>.
          </p>
          <p className="mt-3 text-sm text-white/75">
            Keep going now by adding your own API keys — stored only in your
            browser, sent directly to the APIs, and never counted against the
            free tier.
          </p>
          <div className="mt-5 flex flex-wrap gap-3">
            <a
              href="/settings"
              className="inline-flex items-center gap-2 rounded-lg bg-[var(--orange-accent)] px-5 py-2.5 text-sm font-extrabold uppercase tracking-wide text-white transition hover:bg-[var(--orange-dark)]"
            >
              Add your API keys
            </a>
            <a
              href="https://github.com/willscott-v2/ontologizer-next"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 rounded-lg border border-white/30 px-5 py-2.5 text-sm font-semibold text-white/90 transition hover:bg-white/10"
            >
              Self-host on GitHub
            </a>
          </div>
        </div>
      </div>
    </div>
  )
}

function FaqSection() {
  const faqs: { q: string; a: React.ReactNode }[] = [
    {
      q: 'Why is it called The Ontologizer?',
      a: (
        <>
          An <strong>ontology</strong> is a shared vocabulary for describing
          the things in a subject area and how they relate —{' '}
          <em>Person</em>, <em>Organization</em>, <em>Product</em>,{' '}
          <em>author</em>, <em>offers</em>, and so on.{' '}
          <a
            href="https://schema.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Schema.org
          </a>{' '}
          is the biggest ontology on the web: a vocabulary Google, Microsoft,
          Yahoo, and Yandex agreed to so a machine reading your page can tell
          that &ldquo;Apple&rdquo; means the company and not the fruit, and
          that a review belongs to a specific product.
          <br />
          <br />
          Ontologizer turns your unstructured page content <em>into</em>{' '}
          ontology-friendly structured data — it finds the entities, resolves
          them against Wikipedia, Wikidata, and Google&apos;s Knowledge Graph,
          and emits JSON-LD aligned with the right schema.org types. The
          clearer your entities are, the better search engines and AI
          Overviews can figure out what your page is actually about — and the
          more likely you are to be surfaced correctly instead of skipped or
          hallucinated.
        </>
      ),
    },
    {
      q: 'What is entity-based SEO and why does it matter?',
      a: (
        <>
          Search engines no longer rank pages purely on keywords — they map
          content to <strong>entities</strong> (people, places, products,
          concepts) in a knowledge graph. Pages that clearly signal which
          entities they cover, and how those entities relate, win more of the
          long-tail and AI-Overview surface area. Ontologizer shows you which
          entities Google is likely to recognize on your page, and which ones
          are ambiguous or missing.
        </>
      ),
    },
    {
      q: 'How is this different from a regular schema generator?',
      a: (
        <>
          Most schema tools ask you to fill out a form and spit out JSON-LD
          from the fields you typed in. Ontologizer reads your actual page,
          resolves entities against Wikipedia, Wikidata, and Google&apos;s
          Knowledge Graph API, and uses those <em>sameAs</em> references to
          build schema that ties your content to external identifiers search
          engines already trust.
        </>
      ),
    },
    {
      q: 'What is query fan-out and should I use it?',
      a: (
        <>
          Google&apos;s AI Mode decomposes a user query into many sub-queries,
          then synthesizes an answer across them. The fan-out analysis
          simulates this: it lists the sub-queries your page is likely to get
          pulled into, and whether the page has good, partial, or no coverage
          for each. It&apos;s the fastest way to find content gaps that block
          you from being cited in AI answers.
        </>
      ),
    },
    {
      q: 'Does adding JSON-LD actually help with AI-powered search?',
      a: (
        <>
          Structured data helps — it&apos;s not a magic ranking lever, but it
          reduces ambiguity. When Google&apos;s system can tell that
          &ldquo;Apple&rdquo; on your page is <em>Apple Inc.</em> and not the
          fruit, you&apos;re more likely to be surfaced correctly and less
          likely to be hallucinated off of. Pair JSON-LD with clear on-page
          entity mentions and supporting content for best results.
        </>
      ),
    },
    {
      q: 'What do you do with my data?',
      a: (
        <>
          If you&apos;re signed in, we log the URLs you analyze against your
          account — Search Influence uses this to follow up with people who
          might want help shipping their findings. Nothing is sold, nothing
          is shared with third parties, and if you never want the follow-up,
          let us know via the Feedback button.
          <br />
          <br />
          If you&apos;re using your own API keys without an account, only the
          entity enrichment cache is touched (shared across all users, keyed
          by entity name — Wikipedia lookups for generic terms like{' '}
          <em>SEO</em> and <em>Higher Education</em>). No URL, no analysis
          result, no identifier is stored against an anonymous session.
        </>
      ),
    },
    {
      q: 'What should I do with the recommendations?',
      a: (
        <>
          Treat them as a prioritized checklist. Fixes labeled as E-E-A-T,
          Semantic Coverage, or Topical Authority are usually highest-leverage
          because they also help traditional organic search. If any of this
          feels like a lot,{' '}
          <a
            href="https://www.searchinfluence.com/contact/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Search Influence can help you ship it
          </a>
          .
        </>
      ),
    },
  ]

  return (
    <section className="faq-section">
      <h2 className="mt-12 mb-6 text-2xl font-extrabold text-white">
        SEO &amp; AI-Search FAQ
      </h2>
      <div className="space-y-3">
        {faqs.map((faq, i) => (
          <details
            key={i}
            className="group rounded-lg bg-white/5 border border-white/10 text-white"
          >
            <summary className="flex cursor-pointer items-center justify-between gap-4 px-5 py-4 font-semibold text-white">
              <span>{faq.q}</span>
              <span className="text-[var(--orange-accent)] text-xl transition-transform group-open:rotate-45">
                +
              </span>
            </summary>
            <div className="px-5 pb-5 text-sm leading-relaxed text-white/85">
              {faq.a}
            </div>
          </details>
        ))}
      </div>
    </section>
  )
}
