import type { AnalysisResult } from '@/lib/types/analysis';

const TOOL_URL = 'https://ontologizer.vercel.app/';

function label(value: string): string {
  return value.replace(/([A-Z])/g, ' $1').replace(/^./, (letter) => letter.toUpperCase());
}

function tableCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
}

export function generateMarkdownReport(result: AnalysisResult): string {
  const lines: string[] = [
    '# Ontologizer AI Content Clarity Report',
    '',
    `**Main topic:** ${result.clarity.mainTopic}`,
    `**Topic confidence:** ${Math.round(result.clarity.topicConfidence * 100)}%`,
    `**Overall clarity:** ${result.clarity.overallStatus}`,
    `**Analyzed:** ${result.analyzedAt}`,
    `**Source:** ${result.source.url ?? 'Pasted content'}`,
    `**Analysis version:** ${result.clarity.analysisVersion}`,
    '',
    '## Priority actions',
    '',
  ];

  const priorityActions = result.recommendations.slice(0, 3);
  if (priorityActions.length === 0) {
    lines.push('No evidence-backed priority action was generated.', '');
  } else {
    for (const [index, recommendation] of priorityActions.entries()) {
      lines.push(`${index + 1}. **${recommendation.action}**`);
      lines.push(`   - Observation: ${recommendation.observation}`);
      lines.push(`   - Priority: ${recommendation.priority}; effort: ${recommendation.effort}; confidence: ${recommendation.confidence}`);
      lines.push(`   - Evidence: ${recommendation.evidence.join(', ')}`);
    }
    lines.push('');
  }

  lines.push('## AI Content Clarity', '');
  for (const [name, dimension] of Object.entries(result.clarity.dimensions)) {
    lines.push(`### ${label(name)}: ${dimension.status}`, '', dimension.summary, '');
    for (const check of dimension.checks) {
      lines.push(`- **${check.label} (${check.status}):** ${check.detail}`);
    }
    lines.push('');
  }

  if (result.entities.length > 0) {
    lines.push('## Entities', '', '| Name | Type | Confidence | Wikipedia | Wikidata |', '|---|---|---:|---|---|');
    for (const entity of result.entities) {
      lines.push(`| ${tableCell(entity.name)} | ${entity.type} | ${entity.confidenceScore}% | ${entity.wikipediaUrl ?? '-'} | ${entity.wikidataUrl ?? '-'} |`);
    }
    lines.push('');
  }

  const artifact = result.schemaArtifact;
  lines.push(
    '## Connected schema artifact',
    '',
    `**Status:** ${artifact.status === 'ready' ? 'Ready to review' : label(artifact.status)}`,
    `**Detected page type:** ${artifact.pageType.type} (${Math.round(artifact.pageType.confidence * 100)}% confidence)`,
    `**Schema version:** ${artifact.schemaVersion}`,
    '',
  );
  for (const issue of [...artifact.errors, ...artifact.warnings]) {
    lines.push(`- **${issue.code}:** ${issue.message} Action: ${issue.action}`);
  }
  if (artifact.errors.length || artifact.warnings.length) lines.push('');
  lines.push('```json', JSON.stringify(artifact.jsonLd, null, 2), '```', '');
  lines.push('Generated schema must match visible page content. Review it and validate it with Schema.org Validator and Google Rich Results Test before implementation.', '');

  if (result.fanoutAnalysis) {
    lines.push('## AI Query Coverage', '');
    if (result.fanoutAnalysis.error) {
      lines.push(`AI Query Coverage unavailable: ${result.fanoutAnalysis.error}`, '');
    } else if (result.fanoutAnalysis.analysis) {
      const analysis = result.fanoutAnalysis.analysis;
      lines.push(analysis.disclosure, '');
      for (const question of analysis.questions) {
        lines.push(`- **${label(question.coverage)}:** ${question.question}`);
        lines.push(`  - Intent: ${question.intent}`);
        lines.push(`  - Evidence: ${question.evidenceChunkIds.join(', ') || 'No supporting chunk'}`);
        if (question.gapAction) lines.push(`  - Gap action: ${question.gapAction}`);
      }
      lines.push('');
    }
  }

  if (result.clarity.degradedSteps.length > 0) {
    lines.push('## Analysis notes', '');
    for (const step of result.clarity.degradedSteps) lines.push(`- ${step}`);
    lines.push('');
  }

  lines.push(
    '## About this report',
    '',
    `Generated by [Ontologizer](${TOOL_URL}), a free Search Influence tool for AI content clarity, entity review, and connected schema.`,
    '',
    'The report is ungated. If you want help reviewing or implementing the findings, [contact Search Influence](https://www.searchinfluence.com/contact/).',
    '',
  );
  return lines.join('\n');
}
